# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Wed May 30 14:13:38 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(954, 648)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sentenceList = QtGui.QTableView(self.centralwidget)
        self.sentenceList.setObjectName(_fromUtf8("sentenceList"))
        self.sentenceList.horizontalHeader().setDefaultSectionSize(320)
        self.sentenceList.horizontalHeader().setMinimumSectionSize(100)
        self.sentenceList.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.sentenceList)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.sentenceCorrectionView = QtGui.QTableView(self.centralwidget)
        self.sentenceCorrectionView.setObjectName(_fromUtf8("sentenceCorrectionView"))
        self.sentenceCorrectionView.horizontalHeader().setMinimumSectionSize(80)
        self.sentenceCorrectionView.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.sentenceCorrectionView)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.ControlSet = QtGui.QHBoxLayout()
        self.ControlSet.setObjectName(_fromUtf8("ControlSet"))
        self.sentenceIndexLabel = QtGui.QLabel(self.centralwidget)
        self.sentenceIndexLabel.setObjectName(_fromUtf8("sentenceIndexLabel"))
        self.ControlSet.addWidget(self.sentenceIndexLabel)
        self.sentenceIndex = QtGui.QLabel(self.centralwidget)
        self.sentenceIndex.setObjectName(_fromUtf8("sentenceIndex"))
        self.ControlSet.addWidget(self.sentenceIndex)
        self.startButton = QtGui.QPushButton(self.centralwidget)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.ControlSet.addWidget(self.startButton)
        self.saveButton = QtGui.QPushButton(self.centralwidget)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.ControlSet.addWidget(self.saveButton)
        self.verticalLayout_2.addLayout(self.ControlSet)
        self.TestResult = QtGui.QHBoxLayout()
        self.TestResult.setObjectName(_fromUtf8("TestResult"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.TestResult.addWidget(self.label_2)
        self.testResultPath = QtGui.QLineEdit(self.centralwidget)
        self.testResultPath.setObjectName(_fromUtf8("testResultPath"))
        self.TestResult.addWidget(self.testResultPath)
        self.browseResultPath = QtGui.QPushButton(self.centralwidget)
        self.browseResultPath.setObjectName(_fromUtf8("browseResultPath"))
        self.TestResult.addWidget(self.browseResultPath)
        self.verticalLayout_2.addLayout(self.TestResult)
        self.TrainingSet = QtGui.QHBoxLayout()
        self.TrainingSet.setObjectName(_fromUtf8("TrainingSet"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.TrainingSet.addWidget(self.label_4)
        self.trainingSetPath = QtGui.QLineEdit(self.centralwidget)
        self.trainingSetPath.setObjectName(_fromUtf8("trainingSetPath"))
        self.TrainingSet.addWidget(self.trainingSetPath)
        self.browseTrainingSetPath = QtGui.QPushButton(self.centralwidget)
        self.browseTrainingSetPath.setObjectName(_fromUtf8("browseTrainingSetPath"))
        self.TrainingSet.addWidget(self.browseTrainingSetPath)
        self.verticalLayout_2.addLayout(self.TrainingSet)
        self.CorrectSet = QtGui.QHBoxLayout()
        self.CorrectSet.setObjectName(_fromUtf8("CorrectSet"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.CorrectSet.addWidget(self.label)
        self.correctSetPath = QtGui.QLineEdit(self.centralwidget)
        self.correctSetPath.setObjectName(_fromUtf8("correctSetPath"))
        self.CorrectSet.addWidget(self.correctSetPath)
        self.browseCorrectSetPath = QtGui.QPushButton(self.centralwidget)
        self.browseCorrectSetPath.setObjectName(_fromUtf8("browseCorrectSetPath"))
        self.CorrectSet.addWidget(self.browseCorrectSetPath)
        self.verticalLayout_2.addLayout(self.CorrectSet)
        self.WrongSet = QtGui.QHBoxLayout()
        self.WrongSet.setObjectName(_fromUtf8("WrongSet"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.WrongSet.addWidget(self.label_3)
        self.wrongSetPath = QtGui.QLineEdit(self.centralwidget)
        self.wrongSetPath.setObjectName(_fromUtf8("wrongSetPath"))
        self.WrongSet.addWidget(self.wrongSetPath)
        self.browseWrongSetPath = QtGui.QPushButton(self.centralwidget)
        self.browseWrongSetPath.setObjectName(_fromUtf8("browseWrongSetPath"))
        self.WrongSet.addWidget(self.browseWrongSetPath)
        self.verticalLayout_2.addLayout(self.WrongSet)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.RelabelControl = QtGui.QHBoxLayout()
        self.RelabelControl.setObjectName(_fromUtf8("RelabelControl"))
        self.goodButton = QtGui.QPushButton(self.centralwidget)
        self.goodButton.setObjectName(_fromUtf8("goodButton"))
        self.RelabelControl.addWidget(self.goodButton)
        self.correctButton = QtGui.QPushButton(self.centralwidget)
        self.correctButton.setObjectName(_fromUtf8("correctButton"))
        self.RelabelControl.addWidget(self.correctButton)
        self.badButton = QtGui.QPushButton(self.centralwidget)
        self.badButton.setObjectName(_fromUtf8("badButton"))
        self.RelabelControl.addWidget(self.badButton)
        self.verticalLayout.addLayout(self.RelabelControl)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 954, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.sentenceIndexLabel.setText(QtGui.QApplication.translate("MainWindow", "Sentence Index: ", None, QtGui.QApplication.UnicodeUTF8))
        self.sentenceIndex.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Test Result:", None, QtGui.QApplication.UnicodeUTF8))
        self.testResultPath.setText(QtGui.QApplication.translate("MainWindow", "/home/maluuba/workspace/NLPUtil/python/calendar/trainedStuff/test_result", None, QtGui.QApplication.UnicodeUTF8))
        self.browseResultPath.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Train Set     :", None, QtGui.QApplication.UnicodeUTF8))
        self.browseTrainingSetPath.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Correct Set:", None, QtGui.QApplication.UnicodeUTF8))
        self.browseCorrectSetPath.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Wrong Set :", None, QtGui.QApplication.UnicodeUTF8))
        self.browseWrongSetPath.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.goodButton.setText(QtGui.QApplication.translate("MainWindow", "CF\'s Good", None, QtGui.QApplication.UnicodeUTF8))
        self.correctButton.setText(QtGui.QApplication.translate("MainWindow", "Correct It with CRF", None, QtGui.QApplication.UnicodeUTF8))
        self.badButton.setText(QtGui.QApplication.translate("MainWindow", "Can\'t Handle It", None, QtGui.QApplication.UnicodeUTF8))

